apiVersion: v1
kind: Service
metadata:
  labels:
    app: blink
  name: blink
  namespace: blink
spec:
  type: NodePort
  ports:
  - name: "blink-service"
    port: 5000
    targetPort: 5000
    nodePort: 31000
  selector:
    app: blink
