---
- hosts: all
  roles:
    - k3s-common

- hosts: master
  roles:
    - k3s-master

- hosts: slaves
  tasks:
    - name: join the cluster
      shell: "INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://mc1-{{ansible_local.k3s_stack_id.k3s_stack_id}}-1.sva.local:6443 K3S_TOKEN={{ hostvars['mc1-' + ansible_local.k3s_stack_id.k3s_stack_id + '-1.sva.local']['cluster_token'] }} /mnt/nfs/k3s/install.sh"
      args:
        creates: /etc/rancher/node/password
      when: k3s_master is undefined

- hosts: slaves
  tasks:
    - name: join the huge cluster
      shell: "INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://{{ k3s_master }}:6443 K3S_TOKEN={{ hostvars[k3s_master]['cluster_token'] }} /mnt/nfs/k3s/install.sh"
      args:
        creates: /etc/rancher/node/password
      when: k3s_master is defined
      register: join_command
    - debug: var=join_command.stdout_lines
