---
- hosts: all
  tasks:
    - name: uninstall k3s
      shell: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: yes
    - name: uninstall k3s-agent
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: yes
