---
- name: Install basic packages
  apt:
    pkg:
    - vim
    - curl
    - stress
    - nfs-common

- name: Create custom fact directory
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: create attiny reset script
  copy:
    src:   "attiny-reset.sh"
    dest:  "/usr/local/bin/attiny-reset.sh"
    mode:  0755
    force: yes

- name: mount central nfs
  mount:
    path: /mnt/nfs
    src: 10.198.0.1:/data/nfs
    fstype: nfs
    state: mounted

- name: Set authorized key enrico
  authorized_key:
    user: root
    state: present
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC56k1q+IP4TWuVIvwcB9nrchBx+6h+JRf5PuoujiKhw34OsFbgeQ3fgKkyBYY40VkNvyz5hlFLj+bCPWLv1RBFXWb6Rp3RTcLeayBMiIMTkIMC3lMsPUx/+ZrQE8Q0XXLQJNaQP8+baQ50CykX9y1TJnJ0BZNaxCIXXSiv03IoY+hCOubsOG9GEBKZ/TqbQbcRBiaNF+HIjVIonWlwIQVP8gGFgzzkH6BLfZCcbV2HLfVRit+WQ0wsArz0gzf/+KL4QPBueWpAwG6ShXkjumxSUenfQ1HAW/DxwTTkK+qQrClslRNpph6QieADKqlWqEp3k4LfKWBSmJjh/AG51qeT enricobartz'

- name: Set authorized key rpi-master
  authorized_key:
    user: root
    state: present
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChzoMvguqciXmtoJZee9iFgBt1AG2Bw61xU/hLYH/9YUGrjkHhHpMwlU7+8hUFDcNht3vNo3BNAaZr9Syq0XjQP/cMdEH4gCUCigi7uYkMys7zYCUJ3UY4zs4uPw92CnKyYdGUzxHkpUNQEZZC5TdvBbORgY2PveBnzfHwQPw/U2T/BUUfYFYQAsh4NVZ672RC65G0ubCrW8SEwU88+/ZTmv1DYKHJKWa+KYU40WpbMkls9tuF2l4RcpAvESB6spa8FTm8Y5xl9Yn9RDNQ/sfPCu78a0nAsyUW/1bDDWep3muqY47CATTK40o/9Wk3kJk8ofQEYwDcVNmcLZZz9SPR root@rpi-master'

